config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

  resources :products, only: [:index, :show]

  get '/basket', to: 'baskets#show', as: 'basket'
  post '/baskets/add', to: 'basket_items#create', as: 'add_to_basket'
  delete '/baskets/remove', to: 'basket_items#destroy', as: 'remove_from_basket'

  post '/checkout', to: 'orders#create', as: 'checkout'
  get '/order/:id', to: 'orders#show', as: 'order'

  get '/account/orders', to: 'orders#index', as: 'user_orders'

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  validates :uuid, presence: true
  has_many :basket_items, dependent: :destroy

  def add_unit(unit)
    current_item = basket_items.find_by(unit_id: unit.id)

    if current_item
      current_item.increment!(:quantity)
    else
      current_item = basket_items.create(unit_id: unit.id)
    end

    current_item
  end

  def validate_stock
    basket_items.map(&:validate_stock).uniq == [true]
  end
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  validates :basket_id, :unit_id, :quantity, presence: true
  belongs_to :basket
  belongs_to :unit

  def subtotal_price
    unit.product.price.to_i * quantity.to_i
  end

  def validate_stock
    if quantity <= unit.quantity
      true
    else
      destroy
      false
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :order_items
  validates :subtotal, :total, :status, :user_id, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, dependent: :destroy
  belongs_to :unit
  validates :order_id, :unit_id, :quantity, presence: true
  after_create :decrement_unit_quantity

  private

  def decrement_unit_quantity
    unit.decrement_quantity
  end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :category, :style, :name, :description, :image, :colour, :price, presence: true
  has_many :units, dependent: :destroy

  def self.filter_by_property(category = nil, style = nil, colour = nil)
    return where(category: category, style: style, colour: colour) if category && style && colour
    return where(category: category, style: style) if category && style
    return where(category: category, colour: colour) if category && colour
    return where(colour: colour, style: style) if colour && style
    return where(category: category) if category
    return where(style: style) if style
    return where(colour: colour) if colour

    all
  end

end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :product
  validates :serial_number, :size, :quantity, :product_id, presence: true

  def decrement_quantity
    decrement!(:quantity)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_basket

  private

  def set_basket
    @basket = Basket.find_by!(uuid: session[:basket_uuid])
  rescue ActiveRecord::RecordNotFound
    @basket = Basket.create(uuid: SecureRandom.uuid)
    session[:basket_uuid] = @basket.uuid
  end

  def after_sign_out_path_for(_)
    root_path
  end

  def after_sign_in_path_for(_)
    user_orders_path
  end

end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :set_basket_item, only: [:destroy]

  def create
    @unit = Unit.find(params[:unit_id])
    @basket_item = @basket.add_unit(@unit)

    respond_to do |format|
      if @basket_item.persisted?
        format.html { redirect_to product_path(@basket_item.unit.product), notice: 'Added to basket.' }
        format.json { render :show, status: :created, location: @basket_item }
      else
        format.html { redirect_to product_path(@basket_item.unit.product) }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @basket_item.destroy
    respond_to do |format|
      format.html { redirect_to basket_path, notice: 'Removed from basket.' }
      format.json { head :no_content }
    end
  end

  private

  def set_basket_item
    @basket_item = BasketItem.find(params[:id])
  end

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :subtotal_price, only: [:show]

  def show
  end

  private

  def subtotal_price
    subtotal = @basket.basket_items.sum { |item| item.subtotal_price }
    @basket.update_column(:subtotal, subtotal)
    @basket.update_column(:total, subtotal)
    @basket.update_column(:discount, 0)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = current_user.orders.build(
      shipped_date: Time.now + 2.days,
      delivered_date: Time.now + 4.days,
      subtotal: @basket.subtotal,
      total: @basket.total,
      status: 'Order placed'
    )

    respond_to do |format|
      if @basket.validate_stock && @order.save

        @basket.basket_items.each do |basket_item|
          @order.order_items.create!(
            unit_id: basket_item.unit_id,
            quantity: basket_item.quantity
          )
        end

        @basket.destroy

        format.html { redirect_to order_path(@order), notice: 'Order placed' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { redirect_to basket_path, notice: 'Some items were out of stock and have been removed from your basket' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @categories = Product.distinct.pluck(:category)
    @styles = Product.distinct.pluck(:style)
    @colours = Product.distinct.pluck(:colour)
    @products = Product.filter_by_property(params[:category], params[:style], params[:colour])
  end

  def show
    @product = Product.find(params[:id])
    @variations = Product.where(name: @product.name)
    @sizes = @product.units.pluck(:size)
    @selected_size = params[:size] ? @product.units.find_by(size: params[:size]) : @product.units.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_item_helper.rb
module BasketItemHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/basket_items/_basket_item.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 rounded-md mb-8 shadow-xl px-4 justify-around">
  <div class="mr-6">
    <%= link_to product_path(id: basket_item.unit.product.id) do %>
      <%= image_tag(basket_item.unit.product.image, class: "object-contain", alt: "#{basket_item.unit.product.name}") %>
    <% end %>
  </div>

  <div class="mt-4 mb-12">
    <div class="mb-8">
      <p class="text-xl text-gray-700"><%= basket_item.unit.product.name %></p>
      <p class="text-base text-gray-700"><%= number_to_currency(basket_item.unit.product.price) %></p>
    </div>

    <div class="text-sm text-gray-700 text-opacity-75 mb-8">
      <p><strong>Serial Number: </strong><%= basket_item.unit.serial_number.upcase %></p>
      <p><strong>Colour: </strong><%= basket_item.unit.product.colour %></p>
      <p><strong>Size: </strong><%= basket_item.unit.size %></p>
      <p><strong>Quantity: </strong><%= basket_item.quantity %></p>
    </div>

    <p >
      <%= link_to remove_from_basket_path(id: basket_item.id), method: :delete, data: { confirm: "Are you sure? " } do %>
        <button class="bg-teal-400 hover:bg-teal-600 text-yellow-500 font-bold py-2 px-4 rounded text-lg">Remove Item</button>
      <% end %>
    </p>
  </div>
</div>

app/views/baskets/show.html.erb
<h2 class="text-2xl mt-8 ml-1">Your Basket</h2>

<% if @basket.basket_items.empty? %>
  <section class="section pt-8 text-xl">
    Your basket is empty
  </section>
<% else %>
  <section class="section pt-8">
    <% @basket.basket_items.each do |basket_item| %>
      <%= render(basket_item) %>
    <% end %>
  </section>

  <div class="text-gray-700 text-xl my-16">
    <p>
      <strong>Subtotal:</strong>
      <%= number_to_currency(@basket.subtotal) %>
    </p>
    <p>
      <strong>Discount:</strong>
      <%= number_to_currency(@basket.discount) %>
    </p>
    <p>
      <strong>Total:</strong>
      <%= number_to_currency(@basket.total) %>
    </p>
  </div>

  <% if current_user %>
    <%= button_to 'Checkout', checkout_path,
      method: :post,
      class: "mt-8 bg-teal-400 hover:bg-teal-600 text-yellow-500 font-bold py-2 px-4 rounded text-lg"
    %>
  <% else %>
    <%= link_to 'Checkout', new_user_session_path,
      class: "mt-8 bg-teal-400 hover:bg-teal-600 text-yellow-500 font-bold py-2 px-4 rounded text-lg"
    %>
  <% end %>
<% end %>

<div class="text-lg my-16 text-gray-400 underline hover:text-gray-700">
  <%= link_to 'Continue Shopping', products_path %>
</div>

app/views/home/index.html.erb
<div class="object-contain">
  <%= image_tag('/images/yellowsplash.jpg', alt: "splash-image", class: "hidden md:block") %>
  <%= image_tag('/images/yellowsplash_sm.jpg', alt: "splash-image", class: "md:hidden") %>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-teal-500 text-gray-700 pl-4 py-2 flex flex-row w-full text-base">
  <div class="mr-6">Delivery & Returns</div>
  <div class="mr-6">
    <% if current_user %>
      <%= link_to 'My Account', user_orders_path %>
    <% else %>
      <%= link_to 'My Account', new_user_session_path %>
    <% end %>
  </div>
  <div class="mr-6">Contact</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golden Shoe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div class="sticky top-0 bg-teal-500 w-full pb-0">
      <nav class="flex justify-between">
        <div class="">
          <h1 class="text-3xl text-yellow-500 hover:text-yellow-600 active:text-yellow-600 font-extrabold md:my-1 pl-2 md:pl-6">
            <%= link_to 'Golden Shoe', root_path %>
          </h1>
        </div>
        <div class="pt-3 md:pt-4 pr-2 md:pr-6">
          <%= link_to "Mens", "/products/?category=mens", class: "text-gray-700 text-base hover:text-yellow-600 active:text-yellow-600 mr-2 md:mr-12" %>
          <%= link_to "Womens", "/products/?category=womens", class: "text-gray-700 text-base hover:text-yellow-600 active:text-yellow-600 mr-2 md:mr-12" %>
          <h1 class="text-yellow-500 material-icons text-xl hover:text-yellow-600 active:text-yellow-600" >
            <%= link_to 'shopping_cart', basket_path %>
          </h1>
        </div>
      </nav>
      <div class="bg-teal-200 py-1">
        <h2 class="text-sm text-gray-700 text-center">
          Free shipping and returns on all orders
        </h2>
      </div>
    </div>

    <div class="mx-auto px-4 md:px-8 w-11/12">
      <% if notice %>
        <p class="bg-green-200 border-green-700 text-green-700 rounded-md mt-4 p-2 text-lg"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="bg-red-200 border-red-700 text-red-700 rounded-md mt-4 p-2 text-lg"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golden Shoe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div class="sticky top-0 bg-teal-500 w-full pb-0">
      <nav class="flex justify-between">
        <div class="">
          <h1 class="text-3xl text-yellow-500 hover:text-yellow-600 active:text-yellow-600 font-extrabold md:my-1 pl-2 md:pl-6">
            <%= link_to 'Golden Shoe', root_path %>
          </h1>
        </div>
        <div class="pt-3 md:pt-4 pr-2 md:pr-6">
          <%= link_to "Mens", "/products/?category=mens", class: "text-gray-700 text-base hover:text-yellow-600 active:text-yellow-600 mr-2 md:mr-12" %>
          <%= link_to "Womens", "/products/?category=womens", class: "text-gray-700 text-base hover:text-yellow-600 active:text-yellow-600 mr-2 md:mr-12" %>
          <h1 class="text-yellow-500 material-icons text-xl hover:text-yellow-600 active:text-yellow-600" >
            <%= link_to 'shopping_cart', basket_path %>
          </h1>
        </div>
      </nav>
      <div class="bg-teal-200 py-1">
        <h2 class="text-sm text-gray-700 text-center">
          Free shipping and returns on all orders
        </h2>
      </div>
    </div>

    <div>
      <% if notice %>
        <p class="bg-green-200 border-green-700 text-green-700 rounded-md mt-4 p-2 text-lg"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="bg-red-200 border-red-700 text-red-700 rounded-md mt-4 p-2 text-lg"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/order_items/_order_item.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 rounded-md mb-8 shadow-xl px-4 justify-around">
  <div class="mr-6">
    <%= image_tag(order_item.unit.product.image, class: "object-contain", alt: "#{order_item.unit.product.name}") %>
  </div>

  <div class="mt-4 mb-12">
    <div class="mb-8">
      <p class="text-xl text-gray-700"><%= order_item.unit.product.name %></p>
      <p class="text-base text-gray-700"><%= number_to_currency(order_item.unit.product.price) %></p>
    </div>

    <div class="text-sm text-gray-700 text-opacity-75 mb-8">
      <p><strong>Serial Number: </strong><%= order_item.unit.serial_number.upcase %></p>
      <p><strong>Colour: </strong><%= order_item.unit.product.colour %></p>
      <p><strong>Size: </strong><%= order_item.unit.size %></p>
      <p><strong>Quantity: </strong><%= order_item.quantity %></p>
    </div>
  </div>
</div>

app/views/orders/_order.html.erb
<%= link_to order_path(id: order.id) do %>
  <div class="grid grid-cols-1 md:grid-cols-2 text-sm rounded-md my-8 shadow-xl px-4">
    <p>
      <strong>Order number:</strong>
      <%= order.id %>
    </p>
    <p>
      <strong>Status:</strong>
      <%= order.status %>
    </p>
    <p>
      <strong>Order date:</strong>
      <%= order.created_at.strftime("%d/%m/%Y") %>
    </p>
      <p>
      <strong>Shipped date:</strong>
      <%= order.shipped_date.strftime("%d/%m/%Y") %>
    </p>
      <p>
      <strong>Delivered date:</strong>
      <%= order.delivered_date.strftime("%d/%m/%Y") %>
    </p>
      <p>
      <strong>Subtotal:</strong>
      <%= number_to_currency(order.subtotal) %>
    </p>
      <p>
      <strong>Total:</strong>
      <%= number_to_currency(order.total) %>
    </p>
  </div>
<% end %>

app/views/orders/index.html.erb
<h2 class="text-2xl mt-8 ml-1">Order History</h2>

<div class="mb-8">
  <% @orders.each do |order| %>
    <%= render(order) %>
  <% end %>

  <%= link_to 'Logout', destroy_user_session_path,
    method: :delete,
    class: "my-8 bg-teal-400 hover:bg-teal-600 text-yellow-500 font-bold py-2 px-4 rounded text-lg"
  %>
</div>

app/views/orders/show.html.erb
<section class="section pt-8">
  <% @order.order_items.each do |order_item| %>
    <%= render(order_item) %>
  <% end %>
</section>

<div class="text-gray-700 text-xl mt-16 mb-8">
  <p>
    <strong>Order Number:</strong>
    <%= @order.id %>
  </p>
  <p>
    <strong>Subtotal:</strong>
    <%= number_to_currency(@order.subtotal) %>
  </p>
  <p>
    <strong>Total:</strong>
    <%= number_to_currency(@order.total) %>
  </p>
  <p>
    <strong>Order date:</strong>
    <%= @order.created_at.strftime("%d/%m/%Y") %>
  </p>
  <p>
    <strong>Shipped date:</strong>
    <%= @order.shipped_date.strftime("%d/%m/%Y") %>
  </p>
  <p>
    <strong>Delivered date:</strong>
    <%= @order.delivered_date.strftime("%d/%m/%Y") %>
  </p>
</div>

app/views/products/_product.html.erb
<div>
  <%= link_to product do %>
    <%= image_tag(product.image, class: "object-contain", alt: "#{product.name}") %>
  <% end %>

  <p class="text-xl text-gray-700">
    <%= link_to product.name, product %>
  </p>
  <p class="text-lg text-gray-700 text-opacity-50"
    ><%= "#{product.category.capitalize} #{product.style} #{product.colour}" %>
  </p>
  <p class="text-md text-gray-700 mb-8">
    <%= number_to_currency(product.price) %>
  </p>
</div>

app/views/products/index.html.erb
<div class="mt-8 grid grid-cols-2 md:grid-cols-4 w-full">
  <select class="filter text-lg bg-gray-200 text-gray-700 rounded-sm border-2 border-gray-400 mr-8 py-1" name="category">
    <option selected value>category</option>
    <%= options_for_select(@categories, selected: params[:category]) %>
  </select>

  <select class="filter text-lg bg-gray-200 text-gray-700 rounded-sm border-2 border-gray-400 mr-8 py-1" name="style">
    <option selected value>style</option>
    <%= options_for_select(@styles, selected: params[:style]) %>
  </select>

  <select class="filter text-lg bg-gray-200 text-gray-700 rounded-sm border-2 border-gray-400 mr-8 mt-4 md:mt-0 py-1" name="colour">
    <option selected value>colour</option>
    <%= options_for_select(@colours, selected: params[:colour]) %>
  </select>

  <button class="text-lg bg-gray-200 border-2 border-gray-400 hover:bg-gray-400 text-gray-700 rounded-sm mr-8 mt-4 md:mt-0">
    <%= link_to 'clear', '/products' %>
  </button>
</div>

<section class="grid gap-6 grid-cols-2 md:grid-cols-4 mt-8">
  <% @products.each do |product| %>
      <%= render(product) %>
  <% end %>
</section>

app/views/products/show.html.erb
<div class="grid gap-3 grid-cols-1 sm:grid-cols-2">
  <div class="mt-8">
    <%= image_tag(@product.image, class: "object-contain w-full lg:w-auto", alt: "#{@product.name}") %>
    <div class="flex flex-row mt-8">
      <% @variations.each do |variant| %>
        <%= link_to product_path(variant) do %>
          <div class="rounded-full mr-8 h-8 w-8 border border-gray-400 shadow-xl" style="background: <%= variant.colour %>">
            <span class="hidden"><%= variant.colour %></span>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <div class="mt-8" >
      <p class="text-xl text-gray-700">
        <%= @product.name %>
      </p>
      <p class="text-sm text-gray-700 text-opacity-50">
        <%= "#{@product.category.capitalize} #{@product.style} #{@product.colour}" %>
      </p>
      <p class="text-base text-gray-700 mb-8">
        <%= number_to_currency(@product.price) %>
      </p>
    </div>

    <div class="mt-8 text-lg text-gray-700">
      <select class="filter mr-8 rounded-sm border-2 border-gray-400" name="size">
        <option disabled selected value> select size </option>
        <%= options_for_select(@sizes.sort, selected: @selected_size.size) %>
      </select>
      <%= "#{@selected_size.quantity == 0 ? 'Out of stock' : 'In stock' }" %>
    </div>

    <div class="mt-8 text-lg">
      <%= button_to 'Add to basket', add_to_basket_path(unit_id: @selected_size.id),
        class: "bg-teal-400 hover:bg-teal-600 text-yellow-500 font-bold py-2 px-4 rounded #{@selected_size.quantity == 0 ? 'opacity-50 cursor-not-allowed' : '' }",
        id: "add-to-basket",
        disabled: @selected_size.quantity == 0
      %>
    </div>

    <div class="mt-8">
      <p class="text-xl text-gray-700"><%= "Product Information:" %></p>
      <p class="text-lg text-gray-700 text-opacity-75 lg:max-w-sm"><%= @product.description %></p>
    </div>

  </div>
</div>

<div class="mt-16 mb-16 text-lg text-gray-400 underline hover:text-gray-700">
  <%= link_to 'Back', products_path %>
</div>